name: mirrorchyan

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:

      - id: latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: sanmusen214
          repo: BAAH
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Full package
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: '${{ steps.latest-release.outputs.release }}.zip'
          mirrorchyan_rid: BAAH

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: sanmusen214
          repo: BAAH
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: win
          arch: x64

      - name: Upload update.zip
        uses: MirrorChyan/uploading-action@v1
        if: always()
        with:
          filetype: latest-release
          filename: '*_update.zip'
          mirrorchyan_rid: BAAH

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: sanmusen214
          repo: BAAH
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
